#+TITLE: Grants
#+TODO: TODO(t) TASK(f) EXP(e) | PAUSED(p) DONE(d) 
#+CATEGORY: work
#+TAGS:  allan(a) joel(j) meytar(t) boris(b) BGU(u) maayan(m) adar(d) omer(o) lara(l) hila(h) students(s) itai (i) alexandra (x)
#+STARTUP: overview  inlineimages eval: (org-columns)
#+OPTIONS: toc:nil 


* Grants
** meital meeting
*** 4000 nis for travel soon
*** money allocation- don't want to loose money - ehf and haifa
*** EHF grant says homarim and the grant was for computers
*** grant dates
*** haktzakot
only for 6 months- need to file twice a year.
the filing is done after the 6 months the department paid. ₆In example₆ in october I can file for april-sept
takziv hezeri mehkar - run by uni and this Is where the haktazot money 
** etafnit system for grants
mezahe : tz
kod email
pass email
** EHF grant: birth weight outcomes (#87430411)
   :PROPERTIES:
   :ID:       39e8a4e3-a097-46c4-a3a5-8c35b9452187
   :END:
*** Proposal
    :PROPERTIES:
    :ID:       1de0d538-736c-4312-a083-eeb2d931735a
    :END:
**** preperation
***** use the GIF for birthweight stuff
***** use the CIG/ISF for exposure
**** Grant Aims
***** A1:develop a spatio-tepmoral Ta exposure model in israel
***** A2:look at Ta and outcomes:
-Birth weight
-Lbw
-Preterm
-Defects
-Ultrasound tracking fetal growth
-effect modification and mediation analysis
-Joel: Placental abruption , acute effect that can happen
http://en.wikipedia.org/wiki/Placental_abruption
***** A3:look at interactions between PM and Ta exposures and birth outcomes
*** account number
874304
meytal drori
** Haifa grant (#87448011)
   :PROPERTIES:
   :ID:       f6ccd685-fd83-402f-bbd8-82198406039a
   :END:
*** stats section
-run a poisson regression where we regress counts by zipcode and day (like 10x10 NE) ~1 year lags of the pollutants, and a spline for date (See 10x10 code). this will be run togheter for 10 years
-also to check if the association changed from year to year we will run these exact models by year (IE each year speratley in a seperate model) !note! remember to change the DF for the dats spline for 1 year
!note! once can run the same model instead of yearly in 1 model with all year with interactions so that each pollutant interacts with a year variable, but you need a very large N`
*** first year budget						     :ATTACH:
    :PROPERTIES:
    :Attachments: haifa_grant_yr1_budget.PDF
    :ID:       ab68b195-0ca0-4c4d-87a0-65a818c0a55b
    :END:

)
** CIG (#8736121158)
*** gen info
can be dynamic, that is i can move money from each budget section to another
*** reports
every 3 months we need to put out a reports
you cant supress 200 hours of work (?a month)
cant incl. friday/saturday
no more then 9h a days
teaching etc is > 'other activities'
trips abroad goes under remarks 
** Seed money (#87347711)
END date: 30.9.2016 
account number 87347711 saif 40 
account number 87347711 saif 32 -shonot

** Antonella USA 1x1km grant (# 87443811)
   :PROPERTIES:
   :ID:       5a8c67d0-bd9b-4eff-9d5b-8ae444153490
   :END:
** R21 with Allan Mexico
*** info file
id:
*** code
file:
*** meetings
**** meeting on R21[2015-06-19 Fri 16:00] 
***** Joel: 
ask about both meeting in rome with David 
ask about dinner arrangments
***** allan
send email back to alexei
*** TD

** Andrea/bob built environment grant
*** grant ideas 
**** temperature modeling: showing heat island effects, there could be several degrees c in spatial variblity at night time
**** "greenes" :- use sattelite NDVI (modis/lansat/other) as an exposure (1km-30m) as a proxy for green spaces/areas and
**** walkability
 there are several ways of addressing walkability

 1) simple method gis based method- intersection count, business count, and population density

 residence-level measures of population density

 business counts (as a proxy for accessibility)-Business counts were measured by the counts of all stores, facilities, and services in a participant’s network buffer
 points of interest”, which includes grocery stores, restaurants, banks, hotels, hospitals, libraries, 

 intersection counts (as a proxy for street connectivity)-network buffers around each home address
 Intersection counts were quantified by the number of intersections that were 3-way or greater within each network buffer (Figure 2). A greater intersection count increases the efficiency of walking to destinations. 

 2) developing a more complex model taking into account traffic lanes, traffic direction, walking obstacles, intersections counts etc etc

**** light at night

 DMSP satellite allows 600m resolution. new satellite (NASA-NOAA Suomi National Polar-orbiting Partnership (NPP) satellite) can produce higher res data
 LAN as a exposure and as a potential proxy to residence level pop density

**** web data social/location based services

 whats available in Mexico city/around?
 could be used for: 
 mapping traffic density
 mapping access to health, healthy food, business counts

**** perhaps noise exposure modeling? I have a student that is working on this- tis very hard to model, need a "moitoring campagin", height, buliding material etc
**** crime-data availability?
** ENSANUT mexico grant

** Grant with german group- Josepg
1.  the Volksvaben grant

2.      The Niedersachsen-Israel Research Cooperation Program – I do not know yet when is the next cycle – probably towards the fall – only with institutions in lower Saxony

3.      BMBF (more engineering and less scientific than GIF)

4.    Alexander von Humboldt-Foundation  - We promote academic cooperation between excellent scientists and scholars from abroad and from Germany.

Our research fellowships and research awards allow you to come to Germany to work on a research project you have chosen yourself together with a host and collaborative partner.
If you are a scientist or scholar from Germany you can profit from our support and carry out a research project abroad as a guest of one of more than 26,000 Humboldt Foundation alumni worldwide - the Humboldtians.
As an intermediary organisation for German foreign cultural and educational policy we promote international cultural dialogue and academic exchange.
