* Home
** el al frequent flyer
** apartment 
*** kobi tips for zihron dvarim
check walls for wet spots, gorund sinking
check the price per meter in Lehavim
mashkanta- if there is one how much is it, needs to be less then apartment value
is it registered in tabo/minhal
are there additional work done on the house outside original plans, if so are there permissions?
are there engenring issues that re-occur?
sewage?
is everything build by the book (היטר)
when can they leave the house?
check kvish 6
*** TODO before signing agreement
    :PROPERTIES:
    :ID:       ecc84901-e33e-45c2-8da5-fc6876bccc2a
    :END:
limor lugasi has to check:
האם הבית ממשוכן,משועבד,מעוקל
האש יש טאבו
למי חוץ מהמועצה צריך לפנות
מה ניתן לבנות אישורי זכאות
האם ישנה בניה בלתי חוקית-סטייה מהתוכנית המקורית, יש צורך שיהיה כתוב בחוזה שהוא מסדיר את זה
צריך הצהרה שאין בעיות בדירה שלא נאמרו לנו
*** limor lugasi
054-7777023
*** check arnona halt for reparis until we move in (a maximum of 6 months)
*** payments
| first:  | 410,000 |
| second: | 769,000 |
third: |769,000|
| final: | 437,000 |

| Date   | ammount | done |
|--------+---------+------|
| first  |  410000 | v    |
| second |  769000 | v    |
| third  |  769000 | v    |
| fourth |  437000 |      |
| Total  |         |      |



** diet
*** Low cal veggies
cauliflour
zucchini
mushrooms
brussel sprouts
brocolli
spinich
pumpkin
fennel
celery
carrots


added flavour:
lemons-added flavour with no calories
garlic-same flavour no calories
onions
chili
*** other food to try
beans
qinoa
*** low cal fruits
apples
citrus
*** snacks?
low calorie candies? werters original etc

