#+LAST_MOBILE_CHANGE: 2014-02-15 17:37:29
#+TITLE: TODO
#+TAGS: Fav(f) Most_used(m) PreR(p)
#+STARTUP: overview  inlineimages eval: (org-columns)


* @TODAY@
** how to flatten list to
** work on help dmenu
* Linux
** Org
*** TODO why is org-capture taking ~ 10-20 seconds to come up?
    :PROPERTIES:
    :ID:       f7b6a3d8-b1b4-422f-a05f-4e71ca03dc9e
    :END:
*** capture via gmail
You could also use a %x in a capture template to assist in capturing a   
selection made on your gmail message.  Eg, select Subject: line, then    
capture that to a TODO.                                                  
The other thing that might help would be custom links. Is there a way to form a URL to a gmail message on the web?  If so, you  
could make a "gmail:XXXXX" link that org would expand to a full URL

*** look at hippie expand and add A-/ shortcut
*** create a sparse tree with keybind:
 I am trying to create a keybinding which calls org-match-sparse-tree with the
 (second) argument "-sometag+othertag-TODO=\"DONE\"" -- when I try doing      
 (org-match-sparse-tree nil "-sometag+othertag-TODO=\"DONE\"") via M-x        
 eval-expression, it works correctly (not showing anything where the TODO tag 
 == DONE).  But, if I put the same thing in my init.el file, mapping a        
 keybinding to #'(lambda nil (interactive) (....)), it shows ONLY those items 
*** change date in header
    :PROPERTIES:
    :ID:       a13f3051-ec0b-4b6e-bd55-65a5c4526d38
    :END:
Try setting before-save-hook.  See "(elisp) Saving Buffers".

-Dave

http://lists.gnu.org/archive/html/emacs-orgmode/2013-07/msg01015.html
*** send to "kitchen tablet" recipe
*** make a disable/enable org-inline function (refresh images)
*** check org sync with goog using webdav
    :PRO:PROPERTIES:

           eb0b0883-9d41-4e9d-8d10-7a86532ef458
    :
httpww.osomac.com/2013/09/23/org-mode-moving-forward/
*** export to odf dosent work 
*** make a code block read only
    :PROPERTIES:
    :ID:       5e59de3b-e7ec-4a8d-b1a1-b2d6dbf8cd01
    :END: 
*** correct commenting out in bable org mode
    :PROPERTIES:
           70bb57cd-7f7e-49a7-9ccf-2bc83510b8a8
    : 
*** google calander sync
    :PROPERTIES:
           dd512bb5-813c-4311-a8a4-1f6b651b6e9a
    :
httpgithub.com/dengste/org-caldav
*** Using ido-mode for org-refile
    :PROPERTIES:
           27d1b0f9-dfea-4382-9bde-0df4e4cfd3b4
    :
Usino-mode for org-refile (and archiving via refile)

First up ido-mode, for example using:

; uso mode for completion
(seto-everywhere t)
(seto-enable-flex-matching t)
(seto-max-directory-size 100000)
(idoe (quote both))

Now nable it in org-mode, use the following:

(setg-completion-use-ido t)
(setg-refile-use-outline-path nil)
(setg-refile-allow-creating-parent-nodes 'confirm)

The  line enables the creation of nodes on the fly.

If yefile into files that are not in your agenda file list, you can add them as target like this (replace file1\done, etc with your files):

(setg-refile-targets '((org-agenda-files :maxlevel . 5) (("~/org/file1_done" "~/org/file2_done") :maxlevel . 5) ))

For ling it is often not useful to include targets that have a DONE state. It's easy to remove them by using the verify-refile-target hook.

; Exe DONE state tasks from refile targets; taken from http://doc.norang.ca/org-mode.html
; adcheck to only include headlines, e.g. line must have at least one child
(defy/verify-refile-target ()
  "Ede todo keywords with a DONE state from refile targets"
  (oot (member (nth 2 (org-heading-components)) org-done-keywords)))
    ave-excursion (org-goto-first-child))
  )
(setg-refile-target-verify-function 'my/verify-refile-target)

Now  looking for a refile target, you can use the full power of ido to find them. Ctrl-R can be used to switch between different options that ido offers.

*** Habits mod
    :PROPERTIES:
           b1454b3b-887a-4c7c-8be9-2ab7135ed2d9
    :
httprgmode.org/manual/Tracking-your-habits.html

*** org protocol
    :PROPERTIES:
           6fa053dc-605c-4851-aa83-b0f614f73860
    :
http://orgmode.org/worg/org-contrib/org-protocol.html and http://stackoverflow.com/questions/6681407/org-mode-capture-with-sexp
*** Remember last posiiton of file when reopen/jump to last position
    :PROPERTIES:
           206142d8-4b8c-46e1-aa7c-dad5091871d8
    :
*** BUG This special property is inherited
so if you set it in a level 1 entry, it will apply to the entire tree. When allowed values are defined, setting the corresponding property becomes easier and is less prone to typing errors- NOT WORKING
http://orgmode.org/manual/Property-syntax.html#Property-syntax

*** BUG?? -make new headings appear after the content for the current one do sent work
this
(setq org-insert-heading-respect-content t)

dosent work
*** screenshot app on windows
    :PROPERTIES:
           46648164-8903-44c6-a7cc-12599b55b3af
    :
(defy-org-insert-clipboard ()
  (iactive)
  (l((image-file "clipboard.png")
 (exit-status
  (call-process "convert" nil nil nil
		"clipboard:" image-file)))
    -insert-link nil (concat "file:" image-file) "")
    -display-inline-images)))

Thatks for me (Emacs 24.3, Windows 7) though for practical use some more edge case handling ("don't insert on failure", "different name if file exists") will be wanted.

*** test tags in capture
    :PROPERTIES:
           8beb994b-52e1-4983-8994-c147444cc78a
    :
<201-27 Mon 20:11> :@fav:
*** org-capture for dwb
    :PROPERTIES:
           1244a811-a957-48c4-97f4-a4618ec2b063
    :
<201-29 Wed 17:53>
*** C-x 5 0 > other key
    :PROPERTIES:
           2b274086-00f1-4ec7-90c7-dfaf7c92f876
    :
*** org_build a menu of faces to choose from, or snippets for it (maybe Mymenu)?
    :PROPERTIES:
           f890d27a-3b8f-4fb8-aec1-2e6fcb5e247c
    :
*** auto close capture windows
    :PROPERTIES:
           bf4e7b12-9391-483c-80e6-91cec0f56d13
    :
*** org mail list mails
    :PROPERTIES:
           33e37cd5-beb6-4307-9f8d-5f7a1f4aa1c7
    :
****
-autck empty space between headers
****
linka specific section/codeblock?
****
ready files/headings
****
autoate the date in each level when the level content has changed?
*** style the tags with colors in theme
    :PROPERTIES:
           78fc4737-6075-4b85-8096-aadf6461e6cc
    :
*** org scrape capture/scrape text areas and text+images (In Example a recipe)
*** org scraper project
    :PRO:PROPERTIES:

           4f2569ae-ffb3-4936-b08d-06a614d52b1e
    :
!ide
saveebpage (inluding images)
delell non png and jpeg files
convthat html to org using pandoc
rech the image pathes from XXX to a subfolder with same name as org doc ~/orgfile.org/scrape1

for ', open in emacs to manually scrape with pandoc:
#+besrc js
//!jcript

var ctClone = function()
{
    type = arguments[0];
    root;
    image_count = 0;
    imageMapping = null;

    type == "selection")
    
    var fragment = window.getSelection().getRangeAt(0).cloneContents();
    if (fragment)
    {
        root = document.createElement("span");
        root.appendChild(fragment);
    }
    
    
    
    doc = document.implementation.createDocument(document.namespaceURI, null, null);
    root = doc.importNode(document.documentElement, true);
    
    !root)
    
    return null;
    

    y.prototype.forEach.call(root.querySelectorAll("img"), function(img) {
    imageMapping = imageMapping || {};
    var image = "image_" + image_count++;
    if (/^\/\//.test(img.src))
        imageMapping["http:" + img.src] = image;
    else if (/https?:\/\//.test(img.src))
    {
        imageMapping[img.src] = image;
    }
    else
    {
        imageMapping[location.protocol + "//" + location.hostname + img.src] = image;
    }
    img.setAttribute("src",  image);
    

    rn {
    html : root.innerHTML,
    images : imageMapping
    
};

func spawn(directory, selection)
{
    tmpfile = "/tmp/" + script.generateId() + ".html";
    output = directory + "/tmp.org";
    rite(tmpfile, "w", selection);
    em.spawn("sh -c 'pandoc -s -S " + tmpfile + " -o " + output + "; emacs " + output + "'");
    em.spawn("rm " + tmpfile);
}

func clone(type)
{
    selection = JSON.parse(tabs.current.focusedFrame.inject(injectClone, type));
    !selection)
    return;

    directory = "/tmp/emacs_org_" + tabs.current.mainFrame.domain;
    em.mkdir(directory, 0700);

    pending = 0;
    selection.images)
    
    for (var link in selection.images) {
        var d = new WebKitDownload(link);
        d.destinationUri = "file:///" + directory + "/" + selection.images[link];
        pending++;
        d.start(function(download) {
            switch (download.status)
            {
            case DownloadStatus.finished:
            case DownloadStatus.error:
            case DownloadStatus.cancelled:
                pending--;
                break;
                default : return;
            }
            if (pending == 0)
            {
                spawn(directory, selection.html);
            }
        });
    }
    
    
    
    spawn(directory, selection.html);
    
}
binds", clone.bind(null, "selection").debug(script), "clone_selection");
bindf", clone.bind(null, "full").debug(script), "clone_full");
#+enc

#+BESRC js
//!jcript

func org_protocol_store_link () {
    cmd = 'emacsclient';
    title = tabs.current.title || "" ;
    uri = tabs.current.uri || "";
    args = "'2f6d720053b5240c19cc9c7b35feef5d846ba3a6quot;org-protocol://store-link://" +
    encodeURIComponent(uri) +
    "/" +
    encodeURIComponent(title) +
    "2f6d720053b5240c19cc9c7b35feef5d846ba3a6quot;'";
    em.spawn(cmd + " " + args);
}

func org_protocol_capture (w) {
    cmd = 'emacsclient';
    sel = clipboard.get(Selection.primary) || "";
    title = tabs.current.title || "";
    uri = tabs.current.uri || "";
    args = "-n '" +
    "2f6d720053b5240c19cc9c7b35feef5d846ba3a6quot;org-protocol://capture://" +
    encodeURIComponent(uri) +
    "/" +
    encodeURIComponent(title) +
    "/" +
    encodeURIComponent(sel) +
    "2f6d720053b5240c19cc9c7b35feef5d846ba3a6quot;'";
    em.spawn(cmd + " " + args);
}

bind", org_protocol_store_link, "orgstring");
bind", org_protocol_capture, "orgcapture");
#+ENC

*** org sync files
    :PRO:PRO:PROPERTIES:

    :ID:       73a06516-d0eb-4f95-bb59-992cd105453d
    :END:
**** sol1
With Dropbox I've had a some "conflicted copy" issues; this is annoying (and is
the sort of thing that would have been solved much more easily with version
control) but happens very rarely. What I like about this is that my frequent
changes in org files get propagated without the need for an explicit version
control command.


However, for safety and for tracking, I run a nightly job with bazaar where I
commit all changes (this is done in only one of the machines, of course). This
has actually proven extremely useful when, by mistake, I have deleted a complete
subtree and only realized maybe a month later.
**** sol 2
https://github.com/simonthum/git-sync
**** s3
http://translate.google.com/translate?hl=en&sl=auto&tl=en&u=http://www.mkblog.org/2011/12/zwei-rechner-daten-verloren-dokumente-fehlen/
** Emacs
***  explore free-keys (already installed)
m-x free-keys 
***  explore Auto-revert minor mode
    :PRO:PROPERTIES:

           b96bc2ac-6a1e-49bd-b004-e390c2611974
    :
***  auto complete load dictnionary and load specific dictnionary per mode/file
    :PRO:PROPERTIES:

           70706c17-4e2b-4cac-9f86-a82707489fea
    :
***  customize menus/toolbar (color,bold other)
    :PRO:PROPERTIES:

           bf6950a5-a00e-49aa-96bb-42aae627ba9e
    :
***  MOVE to seen refile macro
    :PRO:PROPERTIES:

           62d5c4cc-44a8-48c5-891d-05e5209aad5d
    :
***  ess-sas an r
    :PRO:PROPERTIES:

           7cf88c53-5680-4944-b8b4-5e6a68590d8a
    :
***  crash recvocery
    :PRO:PRO:PROPERTIES:

    :ID:       8ec2dcc5-2eca-4f51-9f9d-e2261dff9a80
    :END:
** org-download
** kde
*** remember quicktile position in application rules
*** kwin script to move all windows in current workspace/sticky windows t
*** sticky on 2nd screen but not primary (1st)
*** auto detect android MTP kde?
** Misc
*** revise password global system
passes> keepss
docs-org
internt pass -last pass

2 pass system

weak-salt21salar
strong-
*** Look at synergy for sharing betwee office pc and laptopz 
*** folding?
  O:PRO:PROPERTIES:

  :       211498e4-1c54-4e56-adec-1cdf20054a88
  D:
**O undo between sessions (persistant undo)
  tate "TODO"       from "HOLD"       [2013-10-04 Fri 11:12]
  O:PRO:PROPERTIES:

  :       420aaf9f-c67f-4447-b6ad-2aebf160503e
  D:
**O bookmark a file with buffer narrow pre included
  O:PRO:PROPERTIES:

  :       5aebeab3-4053-4ce5-b0f3-084b4a2ca7ff
  D:
**O open a file read-only
  O:PRO:PROPERTIES:

  :       c4dc14c3-7e33-40f4-b885-693202d2e9b7
  D:
*** automate git commit with script_cron daily 
*** Conkymanager
   :PRO:PROPERTIES:

          5ce326b6-fbac-4364-b97a-95de5bf25508
   :
*** Remmina
   :PRO:PROPERTIES:

          16d9168c-fcbf-44e4-bc5a-68e9ca87eec9
   :
*** write in DC forum about exe a command like
   :PRO:PROPERTIES:

          74513521-995c-4cca-b877-80a20b932037
   :
*** write DC forum ugly icons
   :PRO:PROPERTIES:

          ea0f747f-40d5-4663-bfc4-6cc6ec229dbd
   :
*** [#A] auto git 'sync' for configs each nigth
   :PRO:PROPERTIES:

          9616e24c-7e16-40fa-84f1-249d72b5bead
   :
*** Dunst color per application
   :PRO:PROPERTIES:

          6948b8bf-bf06-4491-8b91-415161f29cf3
   :
*** Configure terminator
   :PRO:PROPERTIES:

          c2f65195-b6a6-4853-b86e-1bc80b82edaf
   :
*** pipe volume level to dunst on each change
   :PRO:PROPERTIES:

          22a3ed3a-9201-49ef-9e6c-8cd9b39555ab
   :
*** learn Latex <2013-07-29 Mon>
   :PRO:PROPERTIES:

          922aded4-af0a-4ad4-839e-1ac77165ca47
   :
   t with maybe creating CV in LateX
*** [#B] finish setting up bt sync
   :PRO:PROPERTIES:

          99b3ddd5-6efc-434b-a087-904b11cc0344
   :
*** clipboad sense
   :PRO:PROPERTIES:

          f5dd9e7d-f91a-4515-b72e-7925fe0d9ae5
   :
   oclip currently shows primary- IE classic copy commad
*** emacs add dunst support/notify
   :PRO:PROPERTIES:

          ef5347c6-818a-46b7-b338-17480eccd942
   :
*** gmvalut laptop work>transfer to Server
   :PRO:PROPERTIES:

          097eb08f-ef41-43d1-b3fa-08b774b2205c
   :

*** look at lan wakeup for laptop for backup/rsync?
   :PRO:PROPERTIES:

          45239772-46d4-4acc-a505-57c52816f0db
   :
*** Kefox with new bookmark syncing
   :PRO:PROPERTIES:

          b41a5ed1-ddec-4ae0-ba1d-0a33e2039cfc
   :
*** Flexget
   :PRO:PROPERTIES:

          21e79f5e-7652-42de-b0e7-5022c6098124
   :
*** Look into wake on lan
  :PRO:PROPERTIES:

         cb98e9af-f204-40a8-bc39-bd15e767b7e9
  :
wapc at ~6:00 and start rsync/unison etc
*** Serman2
  :PRO:PROPERTIES:

         a508f55a-38d1-4667-96bb-4acfce1c653c
  :
torol systemd etc
*** Dropbox/btsync start/stop script every X minutes
  :PRO:PROPERTIES:

         fbfd1bcd-52fe-4489-8059-e1bad4fafc05
  :
foync can be maybe done with systemctl
*** Xdotool-gui
   :PRO:PROPERTIES:

          d3c75d51-8439-4f8b-bbbc-a2a7172db86d
   :
*** Unison as a backup tool
   :PRO:PROPERTIES:

          0b62e851-9091-4acc-84bc-96fffd80cfae
   :
*** Look at loliclip
  :PRO:PROPERTIES:

         c2077635-fe08-48b0-bcc3-bdd949d052fe
  :
ht/bbs.archlinux.org/viewtopic.php?id=144741&p=1

*** revise gmpc bind doc
   :PRO:PRO:PROPERTIES:

   :ID:       303f603b-225c-42ab-918f-da078adb3b16
   :END:
http://random.sarine.nl/keys.html
+ means add - means probly remove q: question
** Cantata
*** requests
**** file type on player upper bar
**** crashes in cantata when issuin mpc commands
**** keyboard only interface
**** dynamic mode -> add critereas not played in last 2 weeks, from specific playlist etc
** Teiler/dmenu_play
-add a insert and next option (dont kill playlist but play current)
-add dunst feedback
-add a recursive option > select artist>album> play
-minor: adds all albums with same name (₆In Example₆ still life)
** mpd
*** fix my mpd menu
remove starts, update zfav etc/tmpfiles
** beets
- cant get original_year: yes to work , ₆In Example₆ aqualung jethro tull always defaults to 1984
-create a rating field
-copy comments to that field
-create a demnu entry to my mpd script to rate the current playing song
- get switches for beet import for multiple scenarios (₆In example₆ single:)
** ranger
*** save session?
*** how to press return in a console command
** worker
*** colored tabs
option to color tab by name/location/other
*** copy to clip/paste from clip?
*** copy folder structure
i tried this with no success:
find * -type d -exec mkdir {op}\{\} \;
*** cant make sense of launch menu, i try using PROGRAM FILENAME with no sucess
In example  vlc /home/zeltak/test.mkv
but that dosent do anything, what am i missing here?
*** Filter indicator
*** Toggle sort mode
is there a way toggle a sort mode, so that the same button pressed once would sort asecding and then second press descinding? if not is there a way to maybe script this
* Home
** el al frequent flyer
** apartment 
*** kobi tips for zihron dvarim
check walls for wet spots, gorund sinking
check the price per meter in Lehavim
mashkanta- if there is one how much is it, needs to be less then apartment value
is it registered in tabo/minhal
are there additional work done on the house outside original plans, if so are there permissions?
are there engenring issues that re-occur?
sewage?
is everything build by the book (היטר)
when can they leave the house?
check kvish 6
*** TODO before signing agreement
    :PROPERTIES:
    :ID:       ecc84901-e33e-45c2-8da5-fc6876bccc2a
    :END:
limor lugasi has to check:
האם הבית ממשוכן,משועבד,מעוקל
האש יש טאבו
למי חוץ מהמועצה צריך לפנות
מה ניתן לבנות אישורי זכאות
האם ישנה בניה בלתי חוקית-סטייה מהתוכנית המקורית, יש צורך שיהיה כתוב בחוזה שהוא מסדיר את זה
צריך הצהרה שאין בעיות בדירה שלא נאמרו לנו
*** limor lugasi
054-7777023
*** check arnona halt for reparis until we move in (a maximum of 6 months)
*** payments
| first:  | 410,000 |
| second: | 769,000 |
third: |769,000|
| final: | 437,000 |

| Date   | ammount | done |
|--------+---------+------|
| first  |  410000 | v    |
| second |  769000 | v    |
| third  |  769000 | v    |
| fourth |  437000 |      |
| Total  |         |      |

** diet
*** Low cal veggies
cauliflour
zucchini
mushrooms
brussel sprouts
brocolli
spinich
pumpkin
fennel
celery
carrots


added flavour:
lemons-added flavour with no calories
garlic-same flavour no calories
onions
chili
*** other food to try
beans
qinoa
*** low cal fruits
apples
citrus
*** snacks?
low calorie candies? werters original etc


