# ---------------------------------------------------------------------------
# cn001.py
# Created on: 2011-04-26 11:03:19.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
a2003_001_tif = "C:\\Users\\ekloog\\Documents\\$Doc\\3.PostDoc\\3.1.Projetcs\\3.1.3.TEMP_MODELS\\3.1.1.4.Work\\2.Gather_data\\hdf_2_tiff\\a2003_001.tif"
p2003_001_shp = "C:\\Users\\ekloog\\Documents\\$Doc\\3.PostDoc\\3.1.Projetcs\\3.1.3.TEMP_MODELS\\3.1.1.4.Work\\2.Gather_data\\tiff_2_point\\p2003_001.shp"

# Process: Raster to Point
arcpy.RasterToPoint_conversion(a2003_001_tif, p2003_001_shp, "Value")

