# ---------------------------------------------------------------------------
# cn001.py
# Created on: 2011-04-26 11:57:51.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
a2003_001_shp = "C:\\Users\\ekloog\\Documents\\$Doc\\3.PostDoc\\3.1.Projetcs\\3.1.3.TEMP_MODELS\\3.1.1.4.Work\\2.Gather_data\\tiff_2_point\\a2003_001.shp"
MA_Border = "C:\\Users\\ekloog\\Documents\\$Doc\\3.PostDoc\\3.1.Projetcs\\3.1.3.TEMP_MODELS\\3.1.1.1.Raw_data\\GIS\\GIS_Repo.gdb\\MA_Border"
c2003_001_shp = "C:\\Users\\ekloog\\Documents\\$Doc\\3.PostDoc\\3.1.Projetcs\\3.1.3.TEMP_MODELS\\3.1.1.4.Work\\2.Gather_data\\clip\\c2003_001.shp"

# Process: Clip
arcpy.Clip_analysis(a2003_001_shp, MA_Border, c2003_001_shp, "")

