# ---------------------------------------------------------------------------
# ndv3all.py
# Created on: 2011-05-02 17:17:57.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

for i in range(1, 13):
# Local variables:
  a2003_001_tif = "C:\\Users\\ekloog\\Documents\\$Doc\\3.PostDoc\\3.1.Projetcs\\3.1.3.TEMP_MODELS\\3.1.1.4.Work\\2.Gather_data\\NVDI_TIFF_2_project\\a2003_%03d.tif" % i
  a2003_001_shp = "C:\\Users\\ekloog\\Documents\\$Doc\\3.PostDoc\\3.1.Projetcs\\3.1.3.TEMP_MODELS\\3.1.1.4.Work\\2.Gather_data\\NVDI_TIFF_3_point\\a2003_%03d.shp" % i

  arcpy.gp.RasterToPoint(a2003_001_tif, a2003_001_shp, "Value")

