# ---------------------------------------------------------------------------
# ndv1.py
# Created on: 2011-05-02 16:56:50.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


for i in range(1, 13):
# Local variables:
  MOD_month01_hdf = "C:\\Users\\ekloog\\Documents\\$Doc\\3.PostDoc\\3.1.Projetcs\\3.1.3.TEMP_MODELS\\3.1.1.1.Raw_data\\MODIS_NDVI\\a2003_%03d.hdf" % i
  a2003_001_tif = "C:\\Users\\ekloog\\Documents\\$Doc\\3.PostDoc\\3.1.Projetcs\\3.1.3.TEMP_MODELS\\3.1.1.4.Work\\2.Gather_data\\NVDI_TIFF\\a2003_%03d.tif" % i

  arcpy.gp.ExtractSubDataset(MOD_month01_hdf, a2003_001_tif, "0")

