#+TITLE: Journals


** Environmental health
*** Environmental Research
http://www.journals.elsevier.com/environmental-research/

A Multidisciplinary Journal of Environmental Sciences, Ecology, and Public Health

Environmental Research publishes original reports describing studies of the adverse effects of environmental agents on humans and animals. The principal aim of the journal is to assess the impact of chemicals and microbiological pollutants on human health. Both in vivo and in vitro studies, focused on defining the etiology of environmentally induced illness and to increase understanding of the mechanisms by which environmental agents cause disease, are especially welcome. Investigations on the effects of global warming/climate change on the environment and public health, as well as those focused on the effects of anthropogenic activities on climate change are also of particular interest.

Although Environmental Research is opened to all subjects directly related with this field, areas of special interest include:

• Air, soil, and water pollutants and health
• Biomonitoring and adverse human health effects
• Environmental and occupational medicine
• Environmental epidemiology
• Environmental microbiology
• Environmental toxicology
• Environmental transport and fate of pollutants
• Global warming/climate change
• Nanomaterials in the environment and nanotoxicology
• Risk analysis, risk assessment and risk management, and public health
• Waste treatment and disposal
• Water and wastewater management, and sewage
