** Portugal
*** lisbon
***** food
**** PASTEIS DE BELEM (Rua de Belém, 84-92)				:Fav:
**** TARTINE (Rua Serpa Pinto, 15-A)- good for breakfeast
Portuguese pastries made with the delicate touch of French techniques. We tried their own invention, Chiado (phyllo pastry layered with egg cream) along with Brisa (egg and cream pastry coated with a layer of icing) and Arjun’s favourite: a shortbread tart with a layer of apple compote topped with condensed milk.
**** PASTELARIA ALOMA (Rua Francisco Metrass, 67)- GOOD TO COMBINE WITH START POINT FOR TRAM 28
This pastelaria has won the prize for the best Pastel de Nata two years in a row. Pastelaria Aloma isn’t in a touristy neighborhood, so you’ll find locals popping in for their coffee and pastry at this modest little patisserie. While there were dozens of pasteis de nata lined along the counter, the waitress went into the kitchen to fetch a warm one for us – such a nice touch.
**** Café Beira Gare
http://www.vilamourisca.com/food-travel/blog/2015/04/no-airs-or-graces-just-bubbling-pot-fat
**** Largo de Camões-kiosk
good old fashined soda pop with exotic flavours:
lemongrass (Erva Príncipe) or black currant (Groselha) d
**** CERVEJARIA RAMIRO (Av. Almirante Reis, 1)				:Fav:
This place is shellfish heaven. Fresh tiger prawns, scarlet prawns, crabs, clams, and goose barnacles for the adventurous. All at affordable prices. And you are expected to finish off with a ‘dessert’ or their famous….steak sandwich! We had eaten way too much, but went back for the steak sandwich the next day. They don’t take reservations so be prepared for a very long queue in the evenings, possibly up to an hour on the weekend.
**** TABERNA IDEAL (Rua Esperança 112)
Another excellent Taberna, serving food from the islands of Portugal. Good food, average deserts, large portions and excellent atmosphere packed with locals. Especially loved the pairing of deep fried chorico with sliced oranges and their tartine made with honey, rosemary and fresh cheese.
**** TABERNA DA RUA DAS FLORES (Rua das Flores, 103)			:Fav:
This is my favourite restaurant in all of Lisbon. Favourite. We ate here on our first day. I went back here midweek for their dessert of fresh cheese, honey and almonds. And then, again, we went back there for dinner on our last night in Lisbon because I was worried that no other place might match up, and the pressure of eating well in a city on the last night is always intense. The folks at the restaurant are really nice. Although the menu is written on the chalkboard in Portuguese, they’ll go over everything in English and suggest their recommendations. They have a daily changing menu to keep things exciting. Everything we ate here was superlative, but the one dish I remember so distinctly was the Tiradito de Corvina (fish, a lot like sea bass) barely cooked on hot stones, and raw inside, served on a bed of seaweed, sprinkled with tiny dried prawns and sesame seeds and a dollop of gochujang on the side. And their clams, such good clams with chopped up chourico. I’d say, you can blindly order anything here.
**** CASA DA INDIA (Rua Loreto)
Every time we passed by this restaurant, it was always packed, so we popped in for dinner one evening. Simple, inexpensive, no fuss traditional Portuguese food served (despite the name). A tad greasy for me, but Arjun loved their deep fried sausage.
**** Amorino Baixa-good coconut ice cream
R. Augusta 209
Portugal
**** Chiringuito Tapas Bar
Rua das Trinas 17-19
this is near convention center
http://www.10best.com/destinations/portugal/lisbon/cais-do-sodre-santos/restaurants/chiringuito-tapas-bar/

***** sites
***** TRAM 28
http://lisbon-portugal-guide.com/lisbon-transport/lisbon-tram-28.php
Ride the Tram 28 in Lisbon that takes you through all the famous tourist spots. But careful! It’s known for its pickpockets as well.
The best time to ride the Lisbon Tram 28 is first thing in the morning or early evening when passenger numbers are at the lowest. It is a sad fact that the high levels of tourists gathered in an enclosed space has attracted pickpockets who commonly work the route, so always keep an eye on bags and wallets.
*** Sintra
The owner of the apartment we stayed at described Sintra as “our jewel”. It’s a gorgeous little town with castles and remains of the past. We visited the Pena Palace and Castle of the Moors, both offering fantastic views of the cityscape. There are a few other spots that might be worth a visit, but these are the major ones. There is a train to Sintra from Lisbon (Rossio) every 20 minutes or so. At Sintra, don’t buy a tourist bus ticket to take you to the sights. Rather, hop onto the public bus (turn right after you step out of the train station) and buy a hop-on-hop-off ticket for €5.
**** SAPA (Volta Duche, 12, Sintra)
Close to the train station, Sapa is the place that’s famous for it’s Queijadas, or fresh cheese and coconut filled in a hard, paper thin pastry. Arjun also loved their “Delicias de leite”, their milk custard tart.
**** PIRIQUITA (Rua Padarias, 1/7, Sintra)
The other pastry worth seeking out is a “Travesseiro” at Piriquita. Travesseiro literally means ‘pillow’. And this pillow of puff pastry is filled with an eggy almond cream that’s best had with a shot of espresso.
