Cancer Causes Control (2010) 21:2059--2068 DOI 10.1007/s10552-010-9624-4

ORIGINAL PAPER

Nighttime light level co-distributes with breast cancer incidence
worldwide Itai Kloog • Richard G. Stevens • Abraham Haim • Boris A.
Portnov

Received: 28 April 2010 / Accepted: 20 July 2010 / Published online: 3
August 2010  Springer Science+Business Media B.V. 2010

Abstract Breast cancer incidence varies widely among countries of the
world for largely unknown reasons. We investigated whether country-level
light at night (LAN) is associated with incidence. We compared incidence
rates of five common cancers in women (breast, lung, colorectal, larynx,
and liver), observed in 164 countries of the world from the GLOBOCAN
database, with population-weighted country-level LAN, and with several
developmental and environmental indicators, including fertility rate,
per capita income, percent of urban population, and electricity
consumption. Two types of regression models were used in the analysis:
Ordinary Least Squares and Spatial Errors. We found a significant
positive association between population LAN level and incidence rates of
breast cancer. There was no such an association between LAN level and
colorectal, larynx, liver, and lung cancers. A sensitivity test, holding
other variables at their average values, yielded a 30--50% higher risk
of breast cancer in the highest LAN exposed countries compared to the
lowest LAN exposed countries. The possibility that under-reporting from
the registries in the low-resource, and also low-LAN, countries created
a

I. Kloog  B. A. Portnov (&) Department of Natural Resources &
Environmental Management, University of Haifa, 31905 Mount Carmel,
Haifa, Israel e-mail: portnov@nrem.haifa.ac.il R. G. Stevens University
of Connecticut Health Center, Farmington, CT 06030-6325, USA e-mail:
bugs@uchc.edu A. Haim The Israeli Center for Interdisciplinary Research
in Chronobiology, University of Haifa, 31905 Mount Carmel, Haifa, Israel

spurious association was evaluated in several ways and shown not to
account for the results. These findings provide coherence of the
previously reported case--control and cohort studies with the
co-distribution of LAN and breast cancer in entire populations. Keywords
Breast cancer  Epidemiology  Geography  Light at night (LAN)

Introduction There is evidence that excessive exposure to light at night
(LAN) may increase the risk of breast cancer (reviewed in [1, 2]).
Possible mechanisms include the suppression of melatonin (MLT) secretion
by the pineal gland leading to increased tumor growth [3, 4]; the
adverse effects of LAN on thermoregulatory and immune functions [5, 6],
and the direct disruption of circadian gene function in the
suprachaismatic nuclei by LAN, leading to alterations of cell cycle
regulation in the breast tissue [7, 8]. The original hypothesis was
based on a suppression of melatonin. If this is a primary mechanism,
then we predicted that LAN would be associated with hormone-dependent
cancers (e.g., breast and prostate cancers), and not, or to a lesser
extent, with non-hormone-dependent cancers (e.g., lung, colorectal, and
larynx). The ‘‘LAN--breast cancer'' theory has been supported by the
observation that shift-working women are at higher risk of developing
breast cancer [9--12], while blind women [13--15] and long sleepers
[16--19] seem to be at a lower risk. The studies in shift workers
resulted in the classification of ‘‘shift work'' as a 2A ‘‘probable
human carcinogen'' by the International Agency For Research on Cancer
(IARC) [20].

123

2060

Cancer Causes Control (2010) 21:2059--2068

Fig. 1 Worldwide variation of breast and lung cancers incidence by
continent Note: Age-standardized incident rates per 100,000 Source:
Calculated using data from Ferlay et al. (2004)

Breast cancer is the second leading cause of cancer death in women
(after lung cancer) and is the most common cancer among women worldwide,
excluding nonmelanoma skin cancers. According to the World Health
Organization (WHO), 1,300,000 women are diagnosed with breast cancer
annually and about 465,000 die from this disease every year [21]. Parkin
and colleagues [22--24] conducted several comprehensive studies of
worldwide differences in cancer rates. During this ongoing research, the
estimates of prevalence, mortality, and incidence of 26 most common
cancers were collected for 20 geographic regions of the world. The rates
of breast cancer in women appear to differ widely across the globe,
being generally higher in developed countries than in the developing
ones. Thus, in North America age-standardized rates (ASR) of breast
cancer incidence are 92.7 per 100,000, compared to Africa where breast
cancer ASR are 21.5 per 100,000 (see Fig. 1). Global variation of lung
cancer is also large with ASR reaching 33.85 per 100,000 in North
America vs. 1.61 per 100,000 in Africa. However, to the best of our
knowledge, no studies carried out to date have attempted to investigate
the possibility that the above disparities in female cancer incidence
rates are associated with country-specific LAN emissions (light
pollution), thus testing a prediction of the LAN--cancer theory. In the
present analysis, we investigate whether exposure to LAN is associated
with cancers in women, using ASR of common cancers in women available
for 164 world countries obtained from the GLOBOCAN 2002 database. This
analysis is a continuation of our previous studies showing a significant
co-distribution of LAN and prostate cancer

123

worldwide but not with lung and colorectal cancer in men [25] and an
extension of previous studies which detected a positive association
between LAN and breast cancer within Israel [26]. If LAN is
significantly associated with hormonedependent cancers, then an elevated
incidence of breast cancer with elevated levels of LAN can be expected,
but not elevated risk of colorectal, larynx, liver, and lung cancer, the
cancers which are not hormone dependent and thus included in the present
analysis as negative controls. The limitations of population level, or
ecological, studies are well known and include exposure
misclassification and missing confounder bias. However, such studies are
important in providing context for research among subpopulations of
people using case--control and cohort designs. If no association is
found at the population level in a study with good statistical power,
then that would be evidence against a strong effect of a putative risk
factor. A positive association is thus a necessary, but not sufficient
condition for there to be a large effect of a common exposure on risk in
society at large.

Methods Cancer data Data on cancer ASR in women for the present analysis
were obtained from the GLOBOCAN 2002 database, maintained by the IARC
[23]. The IARC cancer data are reported for individual countries of the
world for the period of 1998--2002 [22]. These data have been previously
used widely in epidemiological research (e.g., [27, 28]).

Cancer Causes Control (2010) 21:2059--2068

2061

The data were obtained for breast, lung, and colorectal cancers (three
of the most common cancers in women) as well as for larynx cancer and
liver cancer the main risk factors for which are well known (smoking for
larynx cancer and hepatitis B virus (HBV) or hepatitis C virus (HCV) for
liver cancer).

was to compare with 2002 cancer incidence rates, the latest available,
thus helping to account, at least to a some extent, for the latency
period between exposure and the onset of cancer. Descriptive statistics
of the research variables used in the analysis are presented in Appendix
1.

Explanatory variables

Data sources

Several development indicators of the world countries were included in
the present analysis as potential predictors of country-specific cancer
incidence rates and perhaps as confounders of any possible LAN effect.
GDP per capita ($US) is a commonly used measure of population welfare
that reflects differences in the diet and lifestyles of different
socio-economic strata [29, 30]. Risk of breast cancer tends to be higher
among high-income groups than across low-income strata and is
significantly higher in the developed countries than in the developing
ones [31].

Data for the present analysis were obtained from the following two main
sources:

Percent urban population Living in cities is often associated with a
considerable amount of physiological stress associated with high
residential densities, traffic congestion, and air pollution, which may
increase cancer risk [32]. In addition, residents of urban areas are
exposed to more environmental smoking, due to high residential densities
thus also creating passive smokers under these conditions, which is
another cause of cancer [33]. Dietary differences and reduced physical
activities associated with urban living may also play a role in the
development of cancer. Electricity consumption (kWh per capita)
Electricity consumption may be an indicator of socioeconomic development
and industrial emission of gaseous substances associated with
electricity production [34, 35]. Fertility rates (average number of
births per woman) Fertility is negatively associated with breast cancer
risk [36]. Fertility rates used in the analysis, to account for this
effect, are total fertility rate (TFR), which is a more accurate measure
of fertility than crude birth rates, since they refer to the average
number of births per woman, rather than to average natural growth for
population as a whole [37]. In addition, LAN exposure was measured in
the analysis using satellite image data, as further detailed in the
‘‘Data Sources'' and ‘‘GIS Analysis'' sections. In particular, the
worldwide satellite image for 1996/97, used in the analysis,

•

•

Country-level data on per capita gross domestic product (GDP), percent
of urban population, and per capita electricity consumption for
1998--1999 were obtained from the ESRI ArcGIS TM database, and
countryspecific fertility rates were obtained from the CIA World Fact
Book [37, 38]. Data on nighttime illumination (LAN) were obtained from
the U.S. Defense Meteorological Satellite Program (DMSP) [39]. The DMSP
satellite provides continuous reading of the entire Earth surface during
nighttime as it cycles around the globe. The satellite image for
1996/97, used in our analysis, was constructed by the DMSP by averaging
daily readings of the satellite sensors and removing cloud cover.
[Reported in nanowatts per centimeter squared per steradian.]

Geographic information systems (GIS) analysis GIS has been used
extensively in recent years as an important research tool for
cancer-related studies [26, 40-- 44]. In the present study, GIS
technology was used for matching country-specific cancer incidence rates
with the LAN levels obtained from satellite images. The task was
performed using the ‘‘spatial join'' tool in the ArcGIS 9.xTM software,
which joins data from two geographic layers by appending attributes from
one layer to another, based on the relative location of features in the
layers [45]. The ‘‘spatial join'' between two data sources was performed
as follows: At the beginning, a worldwide radiancecalibrated satellite
image of nighttime illumination, comprised of average nightlight
intensity in 1996/97 and measured in light radiance units (i.e.,
nanowatts/cm2/sr), was imported to the ArcGIS 9TM software. The image
reflects the fraction of light escaped into space and detected by the
satellite's sensors. Although these satellite measurements are a
magnitude lower than actual LAN levels detected on the ground, they
represent accurately the relative levels of nightlight intensity
observed in different localities [26], thus reflecting the

123

2062

levels of nighttime illumination from various outdoor sources to which
local residents are exposed. The original nighttime illumination image
was converted into a vector map using ArcGIS 9.xTM ‘‘raster-tofeature''
conversion tool. The conversion resulted in a polygon layer containing
approximately 3,800,000 polygons characterized by various LAN
intensities (with a minimum LAN value of 0 (no illumination) and the
maximum value of 255 nanowatts/cm2/sr (maximum illumination). Using the
average LAN exposure in a country may result in a bias caused by a
country's differences in geography and population structure. For
example, countries with large unpopulated areas (such as e.g., Canada or
Sweden) are likely to exhibit disproportionately low average LAN
estimates. To minimize this bias, we used a previously developed novel
method of adjusting LAN exposure, which takes into account both a
country's geographic distribution of population and its local LAN
intensities [46]. To perform this adjustment, the map of LAN intensity
polygons was overlapped with another map containing places worldwide
with a population greater than 1,000 residents. Each city was mapped
using its ‘‘central reference'' point, normally represented by the
location of the city hall or the central post office. Average LAN values
were then calculated for each populated place by obtaining LAN values
from the LAN intensity polygon into which the populated place falls.
Representing big cities by their ‘‘central reference points'' may
potentially lead to a certain overestimation of the calculated average
LAN exposures due to the fact that cities' central areas are normally
more lighted up than their peripheral neighborhoods. However, it is
unlikely to cause a substantial bias in the comparative analysis since
the same procedure was applied to all localities in all countries under
study. Moreover, this approach may be considered compensatory for the
exclusion of populated places with less than 1,000 residents, omitted
from the analysis due to restrictions on data availability. The
difference between simply averaged and population-adjusted LAN estimates
can be considerable. For example, calculating the LAN exposure for
Canada by simple averaging values of LAN polygons (that is, without
accounting for the skewed geographic patterns of the country's
population), results in relatively low LAN estimates of 6.57
nanowatts/cm2/sr, giving the country rank of 133 (out of 164 countries
in our sample). Concurrently, the population-weighted LAN estimate for
Canada is 122.84 nanowatts/cm2/sr which gives it the second rank among
164 countries in our sample, which reflects better the country's high
development status and the elevated per capita LAN exposure of its
residents. Another example is Sweden, whose unadjusted LAN estimate is
6.08

123

Cancer Causes Control (2010) 21:2059--2068

nanowatts/cm2/sr (rank 128), while population-adjusted LAN is 94.23
nanowatts/cm2/sr, giving it the rank of 5 among 164 countries in the
sample. The locality-specific LAN values obtained were then multiplied
by the population size of localities and summed up for each country
under study and later divided by the total population size of the
country's populated places. This resulted in the average LAN exposure
estimate per person in each country under study. Several countries are
reported in Appendix 2. Statistical analysis To identify and measure the
significance of factors affecting the selected cancer rates, several
statistical techniques were used. We started with an ordinary least
squares (OLS) model. During the analysis, multicollinearity and
normality were tested, and their results were found satisfactory
(Tolerance [ 0.27). The tolerance statistic estimates the degree of
inter-collinearity between independent variables, with values
approaching zero, indicating that a strong multicollinearity may be
present. In econometric studies, tolerance values greater than 0.1 are
considered to be satisfactory [47]. The tolerance value of 0.27 we
obtained is considerably higher than 0.1, thus indicating that the
multicollinearity between the explanatory variables is well within
acceptable limits. The analysis was performed separately for each cancer
type using the following linear model: Cancerincidence rate ¼
B0ðconstantÞ þ B1  ðElectricity consumptionÞ þ B2  ðGDP per capitaÞ þ
B3  ðLANÞ þ B4  ðPercent of Urban populationÞ þ B5  ðfertility rateÞ
þ eðrandom error termÞ where B0, . . ....,B5 are regression
coefficients. The residuals of the OLS model were tested for the
presence of spatial autocorrelation using the Moran's I test statistic.
The test showed significant clustering of residuals (Moran's indicator:
(0.366--2.461, p  0.001) which necessitated the use of spatial
dependency (SD) models, to take the spatial dependency of residuals into
account and improve the robustness of regression estimates [48]. The
spatial dependency (SD) regression modeling was performed in the GeoDaTM
spatial analysis software [49]. [It should be noted that the results of
the SD modeling were found to be essentially similar to the OLS
estimates and are not reported in the following discussion, for
brevity's sake, and can be obtained from the authors upon request. In

Breast(2): Breast cancer OLS model; five ‘‘outlier'' Gulf States are
omitted

Breast(1): Breast cancer OLS model; all countries in the sample

Moran's I index of spatial association of regression residuals d

** Indicates a 0.05 significance level; *** indicates a 0.01
significance level

Tolerance (multicollinearity diagnostic)

Regression coefficient (t-statistic in the parenthesis)

Number of valid observations list-wise c

b

Moran's I

a

3.689***

-1.101 0.336 2.461* 3.031*/ 5.130/**

0.105

d

3.775***

0.574 59.893*/ 42.777/* 41.975*** F

56.219***

0.018

164 164

0.655 0.575

164

0.571 R2

159 164 Number of obs.c

0.648

164

0.424

0.911

0.271 -1.016 (-1.242)

0.585 (1.386) -0.042 (-0.971)

-0.127 (-1.517) 3.981 (4.974)***

-1.757 (-4.255)*/ -1.233 (-4.052)/*

1.465 (2.483)* 9.314 (4.824)**

-1.080 (-1.035)

7.882 (3.817)***

-2.939 (-2.759)***

GDP per capita (ln), $US

Fertility rates (per 1,000)

-0.003 (-0.099) 0.003 (0.951) 0.032 (1.126) 0.187 (2.689)*** 0.115
(1.541) Urban population (%)

0.016 (0.743)

0.702 -0.006 (-0.227)

0.619 (0.703) 8.50E--005 (0.496) 0.002 (1.420) 0.002 (0.603) 0.006
(1.317) Electricity consumption (kWh per capita)

0.006 (5.351)***

11.415 (1.604) 1.735 (2.392)**

-7.55E--006 (-0.003) 0.026 (1.061)

-16.896 (-2.426)**

0.150 (2.365)**

0.032 (1.772)

-46.559 (-2.721)*** -25.038 (-1.394) (Constant)

Light at night (LAN) (nanowatts/cm2/sr)

-2.613 (-0.509)

Larynxa Colona Lunga Breast(2)a Breast(1)a Variable

Table 1 Factors affecting most common cancer incidence rates in women
worldwide (method: ordinary least square (OLS) regression)

Table 1 shows factors associated with cancer incidence rates. The
multicollinearity of all variables was tested and found within tolerable
limits (Tolerance [ 0.27). All models in Table 1 are OLS, estimated
separately for the following five cancer types: breast, colorectal,
larynx, liver, and lung. Two regression models (1 and 2) are reported
separately for breast cancer incidence rates. These models differ in
that Model 2 omits the five ‘‘outlier'' Gulf States. The models for
breast, lung, and colorectal cancers provide good fit (R2 =
0.571--0.648) and have a high degree of generality (F = 41.975--59.893,
p  0.01), while the liver and larynx models present poor fits
(0.018--0.125), thus implying that predictors included in these models
do not explain well the variability of these cancer types across the
globe. Among all the cancer types analyzed, only breast cancer exhibited
a significant positive association with LAN exposure (b = 0.150, t =
2.365; p  0.05). For all other cancer types, LAN exposure was found not
to be statistically significant. Per capita GDP (ln) is also positively
associated with ASRs of breast, lung, and colorectal cancer (p  0.01),
while it is inversely associated with liver cancer, albeit the
association is not significant (p [ 0.05). Fertility rates are
negatively associated with breast cancer as well as lung and colorectal
cancer (p  0.01), but not with larynx and liver cancer (p [ 0.3), as
could be expected. To investigate whether the LAN--breast cancer
association differs by countries with different reproductive patterns,
the ANOVA analysis was run. For the analysis, the countries in our
sample were grouped into low, medium, and high fertility based on Jenk's
‘natural breaks' method [50]. This method determines the best
arrangement of values into classes by comparing the sum of squared
differences of values from the means of their classes and thus
identifies ‘‘break points'' in the data values by picking the class
breaks that best group similar values and maximize the differences
between classes. The fertility cut-points were less than 2.67 children
per woman (low-fertility group), 2.67--4.58 children per woman
(medium-fertility group), and greater than 4.58 children per woman
(highfertility group). Notably, the LAN/breast cancer connection is much
stronger in the low-fertility group (F = 16.91, p  0.001), to which most
developed countries of the world belong, than in high-fertility group (F
= 1.24, n.s).

Livera

Results

0.277 (4.330)***

addition, a weighted analysis using the country population was also
conducted and made no meaningful difference in the parameter estimates].

0.475

2063 Toleranceb

Cancer Causes Control (2010) 21:2059--2068

123

2064

Cancer Causes Control (2010) 21:2059--2068

However, in the high-fertility group, five countries had relatively high
LAN exposure, and these were all oil producing Gulf states--Saudi
Arabia, Oman, United Arab Emirates, Qatar, and Kuwait (see Appendix
1-B). When these are removed from the analysis, the strength of
association between LAN and breast cancer of all countries combined (n =
159) considerably increased (from t = 2.365; p  0.05 (Breast(2) Model)
to t = 4.330; p  0.001 (Breast(3) Model; see Table 1).

Sensitivity test To estimate the relative contribution of LAN to breast
cancer ASRs, we split all the countries in our sample into three
groups---countries with minimal LAN exposure (less than 15
nanowatts/cm2/sr); countries with average LAN exposure (15--57
nanowatts/cm2/sr), and countries with the highest LAN exposure (greater
than 57 nanowatts/cm2/sr). The Jenks ‘‘natural breaks'' method was used
to classify countries into the groups. Next, the values of all other
variables from the second model (apart from LAN) were set constant to
the average values observed in each group, and a sensitivity test of
breast cancer ASRs to changes in LAN values was run, using the ‘‘breast
cancer'' model reported in Table 1. The results of the sensitivity test
are reported in Table 2. As Table 2 shows, when the values of all other
variables are fixed, the increase of LAN from 8.60 nanowatts/cm2/sr (the
average LAN value in the group of countries with minimal LAN exposure)
to 28.95 nanowatts/cm2/sr

Table 2 Sensitivity test of breast cancer ASR to plausible changes in
the ground LAN intensity LAN level

Average LAN value (nanowatts/ cm2/sr)

Estimated ASR (per 100,000 residents)

Percent change (%)

Breast (1) model (see Table 1) Low

8.60

40.47

--

Medium

28.95

43.39

7.20

High

99.21

53.43

23.25

Breast (2) model (see Table 1) Low

8.60

44.45

Medium

28.95

50.08

12.70

--

High

99.21

69.54

38.85

ASR-Age-standardized rates per 100,000 residents The values of the fixed
variables were set constant as follows: GDP per capita = $US 9,000 (the
average value for the ‘‘high-resource'' countries under study); Urban
population = 65.3%, Electricity consumption per capita = 131.870 kWh,
fertility rate = 3.4 per 1,000 births

123

(countries with average LAN exposure) corresponds to an increase of 7.2%
in breast cancer ASR. A further increase in LAN value to 99.21 (the
maximum LAN exposure) corresponds to an increase of 23.25% in breast
cancer ASR. There were five countries that had high fertility but also
very high LAN exposure; these were all five Persian Gulf States (Saudi
Arabia, Oman, United Arab Emirates, Qatar, and Kuwait). When these five
‘‘outlier'' Gulf States are omitted (Breast (2) model), the estimated
breast cancer ASRs rise by about 50% from the highest to the lowest LAN
countries. We also fitted the model to the 80 countries with a per
capita GDP of [ $3,000 in order to partially control for a possible bias
in the quality of the registries in the GLOBOCAN database. Parameter
estimates were virtually unchanged compared to the full analysis of all
164 countries.

Discussion The results of the present study are consistent with those of
previous studies of LAN and risk [1], and those obtained on a national
scale of breast cancer incidence in Israel [26]. Similar results were
also obtained for another hormonedependent (prostate) cancer on a
worldwide scale for men [25]. We found a significant positive
association between country LAN level and breast cancer incidence, yet
no such association was found for the other cancer types (colorectal,
larynx, liver, and lung) which were used as negative controls. The
results of our analysis also revealed a significant association between
breast, colorectal, and lung cancer and per capita GDP, which is
consistent with the fact that the relative risk of contracting cancer is
positively associated with average income of local residents [29, 30].
Part, but not all, of this excess is probably due to better access to
medical and diagnostic procedures in the ‘‘highresource'' societies
[51--53]. Ecological studies have welldocumented limitations, but they
also have strengths. The analysis included 164 countries of the world
and data on several potentially important co-variables. Due to
limitations on data availability, other risk factors, including
occupation, alcohol consumption, and specific reproductive factors such
as age-at-first birth, were not available for the analyses though the
per capita income variable may capture some of their effects; in
addition, fertility rate may also more specifically capture some of the
inter-country variability in reproductive factors. Smoking may be partly
covered by the percent urban variable and the per capita income
variable, although for breast cancer, if smoking increases risk, it
probably has a very modest effect. Studies have shown that greater
urbanization increases smoking

Cancer Causes Control (2010) 21:2059--2068

2065

[33] and that smoking is strongly linked with socio-economic status [54,
55]. It should, however, be noted that dynamics in population movement
as well as behavioral patterns that limit exposure to LAN were also not
assessed by this study. Such information can be obtained by studies
carried out on a smaller scale such as localities within an urban space,
but not on a global level. Another limitation is in the completeness of
cancer registration in the developing world where LAN exposure is low
and national incidence is extrapolated from data obtained from small
incidence registries within the country. Parkin et al. [56] conducted a
detailed analysis of cancer registration in Kampala, Uganda over the
period 1994--1996 and concluded that ‘‘...it gives reassurance that
published incidence rates are reasonably accurate.'' However, Curado et
al. [57] caution that the cancer registries in low- and medium-resource
countries are more susceptible to underreporting than those in
highresource countries. We addressed this limitation in several ways.
First, we also analyzed four other cancer types which should also suffer
from this possible bias, yet only breast cancer showed a strong
association with LAN. Second, we restricted analysis to the 80 countries
with per capita GDP greater than $3,000 and found that the change in
parameter estimates was negligible. We also restricted analysis to the
73 lowest fertility countries and again found a significant association
of LAN with breast cancer incidence. When low-fertility countries are
analyzed separately as a group, there is a stronger association of LAN
with breast cancer incidence than among the high-fertility countries.
Two aspects of this analysis are important to note. First, the
variability of both LAN and breast cancer incidence is greater in the
low-fertility group of countries (n = 73) than in the high-fertility
group of countries (n = 48), perhaps providing a better opportunity to
observe an effect should one exist. Second, given the legitimate concern
of lower quality registries in the high-fertility countries, the strong
finding in the low-fertility group lessens the concern about reporting
bias accounting for our results. The lack of a strong association of LAN
and incidence of colorectal cancer (CRC) is interesting in light of the
fact

Table 3 Descriptive statistics of the research variables

Variable

that one strong epidemiological study found a significant association of
shift work with CRC [58]. This study was based on evidence that
melatonin influences risk in experimental and clinical models. Another
consideration is that timing of feeding has been shown to have a strong
synchronizing effect in the gut independent of light; whereas daytime
feeding in nocturnal mice reset circadian gene expression in the gut,
the SCN was unaffected and remained synchronized to the light cycle
[59]. The relation of circadian disruption, from lighting and from meal
timing, and CRC deserves more attention. LAN is increasing rapidly in
developing countries but also in developed countries. In order to save
on energy consumption on the one hand and lower CO2 production on the
other, there is a global trend in industrialized countries like the EU
to shift to low-energy consuming non-incandescent lamps. This shift
while indeed saving energy may cause an increase in nighttime light
exposure since these new lamps produce more light per watt of
electricity, particularly in the blue range of the spectrum. This issue
should be addressed by the policy makers in each country. To the best of
our knowledge, the present analysis is the first study to investigate
the relationship between LAN and the incidence of several common cancers
in women worldwide. No single study, ecological or otherwise, can
‘prove' an association is causal. We view this analysis as an important
piece of the evidence based on whether and to what extent LAN explains
the global breast cancer burden. As per the IARC Classification
paradigm, causal inference requires many different kinds of studies from
different designs and perspectives, all evaluated together by the
scientific community that may or may not eventually come to consensus.

Appendix 1 See Table 3.

Measurement unit

Minimum

Maximum

Mean

SD

A. All Countries in the sample* Dependent variables Breast cancer

ASRa per 100,000

3.9

101.1

37.527

22.928

Colorectal cancer

ASRa per 100,000

0.9

42.2

11.935

9.911

Larynx cancer

ASRa per 100,000

0.0

4.1

0.721

0.612

Liver cancer

ASRa per 100,000

0.2

57.3

4.949

6.291

Lung cancer

ASRa per 100,000

0.1

36.1

6.824

6.589

123

2066 Table 3 continued

Cancer Causes Control (2010) 21:2059--2068

Variable

Measurement unit

Minimum

Maximum

Mean

SD

Electricity consumption per capita

kWh per capita

0.01

3,367.42

Fertility rates

average number of births per woman

1.14

7.41

GDP per capita

US$

463

32,021

6,545.73

7,315.17

Light at Night

nanowatts/cm2/sr

0.00

143.34

8.23

22.43

Urban population

% of residents living in urban areas

6.16

100.00

55.16

23.31

Explanatory variables 75.66 3.403

295.29 1.722

B. Subsample of the Gulf States** Dependent variables Breast cancer

ASRa per 100,000

13.20

33.30

25.420

7.974

Colorectal cancer

ASRa per 100,000

3.1

17.50

10.100

5.201

Larynx cancer

ASRa per 100,000

0.0

0.90

0.460

0.336

Liver cancer

ASRa per 100,000

0.60

8.90

3.940

3.349

Lung cancer

ASRa per 100,000

2.30

6.0

4.180

1.578

Electricity consumption per capita

kWh per capita

6.24

102.42

31.862

40.248

Fertility rates

average number of births per woman

2.79

5.72

4.216

1.365

GDP per capita

US$

7,535

22,123

Light at Night

nanowatts/cm2/sr

24.26

115.39

57.210

37.305

Urban population

% of residents living in urban areas

72.51

97.57

86.460

9.50

Explanatory variables

*Total number of countries--164 **Number of countries--5 a

Age-standardized rates per 100,000

Appendix 2 See Table 4. Table 4 Average LAN exposure in selected
countries

Country

Average LAN exposure per person (nanowatts/ cm2/sr)

Bhutan

0.001

Senegal

0.022

India

0.059

Peru

0.554

Egypt

2.028

Argentina

4.501

Israel

10.707

United States

57.540

References 1. Stevens RG (2009) Light-at-night, circadian disruption and
breast cancer: assessment of existing evidence. Int J Epidemiol
38:963--970 2. Kolstad HA (2008) Nightshift work and risk of breast
cancer and other cancers--a critical review of the epidemiologic
evidence. Scand J Work Environ Health 34:5--22

123

14,185.21

6,134.46

3.  Blask DE, Brainard GC, Dauchy RT, Hanifin JP, Davidson LK, Krause
    JA, Sauer LA, Rivera-Bermudez MA, Dubocovich ML, Jasser SA, Lynch
    DT, Rollag MD, Zalatan F (2005) Melatonindepleted blood from
    premenopausal women exposed to light at night stimulates growth of
    human breast cancer xenografts in nude rats. Cancer Res
    65:11174--11184
4.  Srinivasan V, Spence DW, Pandi-Perumal SR, Trakht I, Esquifino AI,
    Cardinali DP, Maestroni GJ (2008) Melatonin, environmental light,
    and breast cancer. Breast Cancer Res Treat 108:339--350
5.  Haim A, Shanas U, Zubidad AS, Scantelbry M (2005) Seasonality and
    seasons out of time-The thermoregulatory effects of light
    interference. Chronobiol Int 22:57--64
6.  Nelson RJ (2004) Seasonal immune function and sickness responses.
    Trends Immunol 25:187--192
7.  Stevens RG, Blask DE, Brainard GC, Hansen J, Lockley SW, Provencio
    I, Rea MS, Reinlib L (2007) Meeting report: the role of
    environmental lighting and circadian disruption in cancer and other
    diseases. Environ Health Perspect 115:1357--1362
8.  Stevens RG, Rea MS (2001) Light in the built environment: potential
    role of circadian disruption in endocrine disruption and breast
    cancer. Cancer Causes Control 12:279--287
9.  Davis S, Mirick DK, Stevens RG (2001) Night shift work, light at
    night, and risk of breast cancer. J Natl Cancer Inst 93: 1557--1562
10. Hansen J (2001) Increased breast cancer risk among women who work
    predominantly at night. Epidemiology 12:74--77
11. Lie JA, Roessink J, Kjaerheim K (2006) Breast cancer and night work
    among Norwegian nurses. Cancer Causes Control 17:39--44
12. Schernhammer ES, Kroenke CH, Laden F, Hankinson SE (2006) Night work
    and risk of breast cancer. Epidemiology 17:108--111

Cancer Causes Control (2010) 21:2059--2068 13. Hahn RA (1991) Profound
bilateral blindness and the incidence of breast cancer. Epidemiology
2:208--210 14. Kliukiene J, Tynes T, Andersen A (2001) Risk of breast
cancer among Norwegian women with visual impairment. Br J Cancer
84:397--399 15. Verkasalo PK, Pukkala E, Stevens RG, Ojamo M, Rudanko SL
(1999) Inverse association between breast cancer incidence and degree of
visual impairment in Finland. Br J Cancer 80:1459--1460 16. Pinheiro SP,
Schernhammer ES, Tworoger SS, Michels KB (2006) A prospective study on
habitual duration of sleep and incidence of breast cancer in a large
cohort of women. Cancer Res 66:5521--5525 17. Verkasalo PK, Lillberg K,
Stevens RG, Hublin C, Partinen M, Koskenvuo M, Kaprio J (2005) Sleep
duration and breast cancer: a prospective cohort study. Cancer Res
65:9595--9600 18. Kakizaki M, Kuriyama S, Sone T, Ohmori-Matsuda K,
Hozawa A, Nakaya N, Fukudo S, Tsuji I (2008) Sleep duration and the risk
of breast cancer: the Ohsaki Cohort Study. Br J Cancer 99:1502--1505 19.
Wu AH, Wang R, Koh W-P, Stanczyk FZ, Lee H-P, Yu MC (2008) Sleep
duration, melatonin and breast cancer among Chinese women in Singapore.
Carcinogenesis 29:1244--1248 20. Straif K, Baan R, Grosse Y, Secretan B,
El Ghissassi F, Bouvard V, Altieri A, Benbrahim-Tallaa L, Cogliano V
(2007) Carcinogenicity of shift-work, painting, and fire-fighting.
Lancet Oncol 12:1065--1066 21. ACS (2007) Global cancer facts and
figures 22. Parkin DM, Bray F, Ferlay J, Pisani P (2001) Estimating the
world cancer burden: Globocan 2000. Int J Cancer 94:153--156 23. Parkin
DM, Bray F, Ferlay J, Pisani P (2005) Global cancer statistics, 2002. CA
Cancer J Clin 55:74--108 24. Parkin DM, Bray FI, Devesa SS (2001) Cancer
burden in the year 2000. The global picture. Eur J Cancer 37(Suppl
8):S4--S66 25. Kloog I, Haim A, Stevens RG, Portnov BA (2009) Global
codistribution of light at night (LAN) and cancers of prostate, colon,
and lung in men. Chronobiol Int 26:108--125 26. Kloog I, Haim A, Stevens
RG, Barchana M, Portnov BA (2008) Light at Night Co-distributes with
Incident Breast but not Lung Cancer in the Female Population of Israel.
Chronobiol Int 25:65--81 27. de Sanjosé S, Diaz M, Castellsagué X,
Clifford G, Bruni L, Muñoz N, Bosch FX (2007) Worldwide prevalence and
genotype distribution of cervical human papillomavirus DNA in women with
normal cytology: a meta-analysis. Lancet Infect Dis 7:453--459 28. Boyle
P, Ferlay J (2005) Cancer incidence and mortality in Europe, 2004. Ann
Oncol 16:481 29. Hulshof KF, Brussaard JH, Kruizinga AG, Telman J, Lowik
MR (2003) Socio-economic status, dietary intake and 10 y trends: the
Dutch National Food Consumption Survey. Eur J Clin Nutr 57:128--137 30.
Hulshof KF, Lowik MR, Kok FJ, Wedel M, Brants HA, Hermus RJ, ten Hoor F
(1991) Diet and other life-style factors in high and low socio-economic
groups (Dutch Nutrition Surveillance System). Eur J Clin Nutr
45:441--450 31. Bray F, McCarron P, Parkin DM (2004) The changing global
patterns of female breast cancer incidence and mortality. Breast Cancer
Res 6:229--239 32. Han X, Naeher LP (2006) A review of traffic-related
air pollution exposure assessment studies in the developing world.
Environ Int 32:106--120 33. Volzke H, Neuhauser H, Moebus S, Baumert J,
Berger K, Stang A, Ellert U, Werner A, Döring A (2006) Urban-rural
disparities in smoking behaviour in Germany. BMC Public Health 6:146

2067 34. Gram-Hansenn K, Petersen NK. Diffrenet everday lives-Differnt
patterns of electrical use. In: ACEEE Summer Study on Energy Efficiency
in Buildings 2004. Pacific Grove, California 35. Jumbe BLC (2004)
Cointegration and causality between electricity consumption and GDP:
empirical evidence from Malawi. Energy Economics 26:61--68 36. Kelsey
JL, Gammon MD (1990) The epidemiology of breast cancer. CA: Cancer J
Clin 41:146--165 37. CIA (2006) ‘‘CIA World Factbook.'' Retrieved 2006,
2006, from http://www.cia.gov/index.html 38. ESRI (2007) ARCGIS. In. 9.2
ed: ESRI 39. DMSP (2004) DMSP Nighttime lights data download 40.
Banerjee S, Wall MM, Carlin BP (2003) Frailty modeling for spatially
correlated survival data, with application to infant mortality in
Minnesota. Biostatistics 4:123--142 41. Krieger N, Chen JT, Waterman PD,
Soobader MJ, Subramanian SV, Carson R (2002) Geocoding and monitoring of
US socioeconomic inequalities in mortality and cancer incidence: does
the choice of area-based measure and geographic level matter?: the
Public Health Disparities Geocoding Project. Am J Epidemiol 156:471--482
42. Maheswaran R, Strachan DP, Dodgeon B, Best NG (2002) A
population-based case-control study for examining early life influences
on geographical variation in adult mortality in England and Wales using
stomach cancer and stroke as examples. Int J Epidemiol 31:375--382 43.
O'Leary ES, Vena JE, Freudenheim JL, Brasure J (2004) Pesticide exposure
and risk of breast cancer: a nested case-control study of residentially
stable women living on Long Island. Environ Res 94:134--144 44. Scott D,
Curtis B, Twumasi FO (2002) Towards the creation of a health information
system for cancer in KwaZulu-Natal, South Africa. Health Place
8:237--249 45. Minami M (2000) ESRI. Using ArcMap: GIS. ESRI, Redlands,
California 46. Kloog I, Haim A, Portnov BA (2009) Using kernel density
function as an urban analysis tool: Investigating the association
between nightlight exposure and the incidence of breast cancer in Haifa,
Israel. Comput Environ Urban Syst 33:55--63 47. Kinnear PR, Gray CD
(2007) SPSS 15 Made Simple. Psychology Press, Philadelphia, PA 48.
Anselin L (1999) Spatial Econometrics. Bruton Center, School of Social
Sciences,University of Texas at Dallas, Dallas 49. Anselin L, Syabri I,
Kho Y (2005) GeoDa: An Introduction to Spatial Data Analysis. Geogr
Ana006C 38:5--22 50. Jenks G (1967) The data model concept in
statistical mapping. Int Yearb Cartogr 7:186--190 51. Bradley CJ, Given
CW, Roberts C (2002) Race, socioeconomic status, and breast cancer
treatment and survival. J Natl Cancer Inst 94:490--496 52. Madison T,
Schottenfeld D, James SA, Schwartz AG, Gruber SB (2004) Endometrial
cancer: socioeconomic status and racial/ethnic differences in stage at
diagnosis, treatment, and survival. Am J Public Health 94:2104--2111 53.
Wells BL, Horm JW (1992) Stage at diagnosis in breast cancer: race and
socioeconomic factors. Am J Public Health 82: 1383--1385 54. Adler N,
Boyce T, Chesney M, Cohen S, Folkman S, Kahn RL, Syme SL (1994)
Socioeconomic status and health: The challenge of the gradient. Am
Psychol 49:15--24 55. Jha P, Peto R, Zatonski W, Boreham J, Jarvis MJ,
Lopez AD (2006) Social inequalities in male mortality, and in male
mortality from smoking: indirect estimation from national death rates in
England and Wales, Poland, and North America. Lancet 368:367--370

123

2068 56. Parkin DM, Wabinga H, Nambooze S (2001) Completeness in an
African cancer registry. Cancer Causes Control 12:147--152 57. Curado
MP, Voti L, Sortino-Rachou AM (2009) Cancer registration data and
quality indicators in low and middle income countries: their
interpretation and potential use for the improvement of cancer care.
Cancer Causes Control 20:751--756 58. Schernhammer ES, Laden F, Speizer
FE et al (2003) Night-Shift work and risk of colorectal cancer in the
Nurses' Health Study. J Natl Cancer Inst 95:825--828

123

Cancer Causes Control (2010) 21:2059--2068 59. Hoogerwerf WA, Hellmich
HL, Cornélisson G et al (2007) Clock gene expression in the murine
gastrointestinal tract: endogenous rhythmicity and effects of a feeding
regimen. Gastroenterology 133:1250--1260


