#+TITLE: Exposure

** Environmental Epi
*** exposure 
**** Exposure error 
three types of exposure measurement error in longitudinal studies of air pollution and health, such as those cited above:
1.The first error is derived from the difference between the daily personal exposures of each individual and the daily community-average personal exposure.
2.The second error stems from the difference between the daily community average personal exposure and the true ambient concentration.
3. the third component of error is from the difference between the measured and the true ambient concentration (i.e., measurement error). 

The first and third types of errors are of the Berkson type. Since Berkson measurement error is such that the true exposure is distributed around the measured value, this form of error will not lead to biased health effect estimates for a given pollutant, but does make the association less significant since relying on the mismeasured surrogate is not as informative as having true exposure.
The second type of error is termed classical and will bias the relative risk.
Upward bias can occur in rare settings where the ratio of the amount of measurement error in PM to the measurement error in the other pollutants is high and the correlations amongthe pollutants are extreme. Hence, the authors concluded that observed PM health risk estimates were likely not biased away from 0 by measurement error.
The second type of error will be influenced by pollution from indoor sources and by the difference between the ambient concentration and the ambient exposure (the ambient component of personal exposure). Since indoor-generated sources are generally uncorrelated with the ambient concentrations, the indoor-generated component of personal exposure will not affect the relative risk due to ambient pollution.  
**** scales of Human exposure
Human exposures can be decomposed to three components: regional, urban background, and microscale.

The impact of the regional sources is uniform across the study area.

The urban background represents the collective emissions of sources within the study area.
Exposures to these emissions depend on the distribution of local sources, their geographic location and the prevailing meteorological conditions. Although these exposures vary by space, their changes are very smooth. 

Finally, the microscale exposures are directly related to nearby sources located within a few hundred meters. These exposures exhibit pronounced spatial variability.

In our study we use two exposure metrics: the first, is the distance of the subject residence from the closest roadway, which can be used as a surrogate of microscale exposures to nearby traffic, and

the second is the PM2.5 exposure at outside the subject residence. This encompasses exposures associated with both nearby traffic and urban background.  Therefore, gradients of the two exposure metrics amongst the cohort subjects will represent differences of the impact of nearby traffic sources, and nearby sources plus urban background. Note that the urban background reflects traffic emissions as well as those from other sources such as home heating, air port and seaport, and a host of small sources.

The above definitions assume that exposures were estimated mostly during the same time period. otherwise, gradients in the two exposure metrics could also reflect temporal trends in emissions of local and/or distant sources. In conclusion, distance from the nearest roadway and pm25 mass estimates are two different exposure metrics where the former represents s a fraction of the latter.

**** chronic vs accute variablity in exposure assesmnt 
 for chronic we care about spatial variability
 for acute we care about temporal variability 

*** PM
**** basics
PM includes both primary particles such as soot and dust from combustion sources and agricultural burning activities, and secondary particles such as sulfate and nitrate generated through chemical reactions in the atmosphere from sulfur dioxide, nitrogen oxide, and ammonia emitted from power plants, industries, automobiles, and agriculture
*** AOD and satellite data
**** base AOD values
0-1 indicates normal AOD days
0.7-1.2 Days where heavy PM concentrations are transported from elsewhere
2-4 Heavy sand stroms days, days in Africa etc
When you see values of 1.2 in Western counties (IE MA) it is most likley clouds
**** aod-pm relatinship
 
However, some discrepancy between AOD and PM were also observed (Koelemeijer et al., 2006; Emili et al., 2010; Li et al., 2011). The reasons for the discrepancy are two-fold: one is the limitation of inversion algorithm for AOD retrieval, potentially causing large bias over areas with high reflectance such as cirrus cloud, urban built-up area, and snow/ice surface etc. Another reason is aerosol composition (e.g. type, size, proportion and vertical distribution) and hygroscopic growth. Nonetheless, AOD has been wildly considered as a good surrogate for surface PM (Wang and Christopher, 2003), especially AOD at 0.47 , which previously reported to have the highest correlation with PM2.5 (Zeeshan and Kim Oanh, 2014).

**** advantages of using AOD data over LUR
the use of physical measuremtns gives us the ability to predict in areas far from physics monitors (such as >30km etc) and reach rural area
use of AOD gives us daily predctions over space where LUR cannot
monitors in modest numbers some areas may be under or unrepresented in calibrating the land use regression.

using Aod results in more parsimonious models then LUR- leaves out some Land use terms used in later health outcome models that can create bias since they are included in the exposure
