#+TITLE: Academic writing

* Writing guides
** General
*** Abbriviatins/latin
i.e -that is
e.g - for example
inter alia- among others
** Manuscript writing
*** syntax
Write in the "third person", i.e. w/o we, i, etc. Start with the general description of the research methodology (what was done and how).
Then turn to the results: follow strictly the research questions stated in the introduction and give answers to each of them.

*** general structure
**** title

Never use "The" in manuscript titles

**** Introduction
usualy devided into 3:

1.previous studies
2.whats lacking/wrong/missing in previous studies
3.what this paper is about/innovated compared to these studies

**** table presentation

*Reporting a Spatial Regression Table for Journals*
 (see attachment)

***** report\_spatial\_reg.pdf

[[Academic_writing_files/attach/report_spatial_reg.pdf][Attachment #01
(report\_spatial\_reg.pdf)]]

**** grammer and tips

*Latin Abbreviation List for articles
*Inter alia - among other things
 Viz-that is; namely.
 Foci-A plural of focus
 Albeit- although; even if: a peaceful, albeit brief retirement
 Ceteris paribus - "all other things being equal."

**** general manuscript template (portnov)

***** outline

*Paper template (by prof Boris Portnov)
*Abstract
 1.
 Introduction ~2 pages
 2.
 Research background ~3-4 pages
 Special Link/ background (in our study Link between MLT, LAN and
Cancer) ~2 pages
 3.
 Research methodology and data sources ~3-4 pages
 4.
 Results
 5.
 Discussion
 6.
 Conclusion
 7.
 References

***** tips

*Intro*

-  don't analyze other results just present them
-  need to show that there is still lack of knowledge in the area
-  talk about constraints and lack of prior research
-  then present 2-3 questions or hypothesis
-  then add this sentence:

The paper starts in a brief discussion .......
 add all the main chapters of the paper
 *Research background*
 Go over each paper that is relevant and analyze each one. what did they
show...summarize each ones findings.
 *Research methodology
*

-  explain the research area (haifa in our case)
-  how did you build the database
-  explain dependent variables and then in a separate section the
   explanatory variables
-  explain GIS
-  explain LAN
-  explain all statistical methods

 *Results
*Show the results clearly following the main tables and by the
methodology order.
 *Conclusions
*summerize results
 whats missing in the research , limitations etc
 state maybe that there are other things to check and this is the first
step

*** hypothesis

**** how to form and write an hypothesis

Writing Hypotheses: a student lesson
 Purpose: to learn when and how to write hypotheses.
 Most students believe that they are going to be experimenting anytime
they are given a laboratory assignment in science. However, more often
than not, students are doing something other than experiments. This is
not necessarily bad. A good deal of science is observational and
descriptive. For example, the study of bio-diversity usually involves
looking at wide variety of specimens and maybe sketching and recording
their unique characteristics. However, there are other times when we
science teachers are trying to teach students how scientists work and
how we can verify things which others may say or believe is so without
any proof.
 To learn about what is not known or to verify a notion, the so-called
"scientific method" might be carried out and an actual experiment may be
conducted. It does not matter that your experiment has been done a
thousand times before or that your teacher already knows the results.
What matters is that you don't know the results and that you can
independently find a verifiable answer. In real experiments, real
hypotheses should be written before the actual experiment.
 What Is a Real Hypothesis?
 A hypothesis is a tentative statement that proposes a possible
explanation to some phenomenon or event. A useful hypothesis is a
testable statement which may include a prediction. A hypotheses should
not be confused with a theory. Theories are general explanations based
on a large amount of data. For example, the theory of evolution applies
to all living things and is based on wide range of observations.
However, there are many things about evolution that are not fully
understood such as gaps in the fossil record. Many hypotheses have been
proposed and tested.
 When Are Hypotheses Used?
 The key word is testable. That is, you will perform a test of how two
variables might be related. This is when you are doing a real
experiment. You are testing variables. Usually, a hypothesis is based on
some previous observation such as noticing that in November many trees
undergo color changes in their leaves and the average daily temperatures
are dropping. Are these two events connected? How?
 Any laboratory procedure you follow without a hypothesis is really not
an experiment. It is just an exercise or demonstration of what is
already known.
 How Are Hypotheses Written?
     Chocolate may cause pimples.
     Salt in soil may affect plant growth.
     Plant growth may be affected by the color of the light.
     Bacterial growth may be affected by temperature.
     Ultra violet light may cause skin cancer.
     Temperature may cause leaves to change color.
 All of these are examples of hypotheses because they use the tentative
word "may.". However, their form is not particularly useful. Using the
word may does not suggest how you would go about proving it. If these
statements had not been written carefully, they may not have even been
hypotheses at all. For example, if we say "Trees will change color when
it gets cold." we are making a prediction. Or if we write, "Ultraviolet
light causes skin cancer." could be a conclusion. One way to prevent
making such easy mistakes is to formalize the form of the hypothesis.
 Formalized Hypotheses example:
 In the statements above the dependent variable is blue and the
independent variable is red.
 If skin cancer is related to ultraviolet light , then people with a
high exposure to uv light will have a higher frequency of skin cancer.
 If leaf color change is related to temperature , then exposing plants
to low temperatures will result in changes in leaf color.
 Notice that these statements contain the words , if and then. They are
necessary in a formalized hypothesis. But not all if-then statements are
hypotheses. For example, "If I play the lottery, then I will get rich."
This is a simple prediction. In a formalized hypothesis, a tentative
relationship is stated. For example, if the frequency of winning is
related to frequency of buying lottery tickets. "Then" is followed by a
prediction of what will happen if you increase or decrease the frequency
of buying lottery tickets. If you always ask yourself that if one thing
is related to another, then you should be able to test it.
 Formalized hypotheses contain two variables. One is "independent" and
the other is "dependent." The independent variable is the one you, the
"scientist" control and the dependent variable is the one that you
observe and/or measure the results.
 The ultimate value of a formalized hypothesis is it forces us to think
about what results we should look for in an experiment.
 Rewrite the first four hypotheses using the formalized style shown
above. Single underline the dependent variable and double underline the
independent variable in the If clause of each hypothesis. When you are
done, write one more original hypothesis of your own using this form.

*** AOD focused

**** key setntemces

All the data are coupled spatially and temporally to build a daily
PM-AOD-METEO dataset for every
 location.
** cv writings
*** Haifa Uni CV writing guide

[[Academic_writing_files/attach/cv_guide.pdf][Attachment #02
(cv\_guide.pdf)]]
 see attached PDF
* Grants 
** BGU RSA grant proposal TIPS
*** ISF
look at the active grants to see whats been funded at the website
its important to choose the correct panel when submitting
the application is not the focus of the proposal but rather the theoretical questions
!abstract is very important!
make sure the keywords are very precise
new researchers can submit also an equipment grant alongside with the "maanak ishi"

in ISF there is no template you start from scratch (see handouts from talk to see the rules)
write a full page of abstract!
you can add 5 figure pages on top of the 10 pages of figures
make sure you have a long bibliography, go crazy as much as you can
about half of the pages (5 for background and objectives and the rest for the other sections)
use the same heading from the aims for the methods
make sure it all reffers to the future (i will etc..)
for ethic issues: say "approval will be requested from the instituonal IRB"
add some perlimanry results, you can add some published work but its important to add perlimanry results
conditions: state the seed money from BGU that will build a lab and all the equpiment
say at the end that you expect at the end of the research to have A,B,C in hand
its important to state the pitfuls and how to address them
you need to contact your budget officer (check of its faculty or isf) to go over the budget
for ISF take !Note! for the bibliography since they have special requierments (see handouts, for example a seperate bib list with * on close to fields refrences)

*** gif young 
the most important section is planned travel to the germany partner
state you would be traveling to the laboratory for prof X
state he is a very well established prof and that he will contribute to helping me write a full gif grant
