#+LATEX_HEADER: \usepackage[mathlf]{MinionPro}
#+LATEX_HEADER: \usepackage[scaled=.875]{inconsolata}

#+TITLE: Recommendation letter on behalf of XXXX
#+AUTHOR: Dr. Itai Kloog



#+CLOSING: Yours truly,
#+SIGNATURE: Itai kloog\\
#+SIGNATURE: The Department of Geography and Environmental Development\\
#+SIGNATURE: Ben-Gurion University of the Negev\\
#+SIGNATURE: P.O.B. 653 Beer Sheva, Israel\\

#+OPTIONS: subject:nil



* Pre                                                              :noexport:

* TO                                                                     :to:
The Full Bright foundation 


* Dear XXXX,
# NOTE: Your letter is the first non-special heading.  The title of  this heading may used as an opening.

#+BEGIN_VERSE
I am pleased to write a recommendation for $1 for the $2.
I have met $1 four years ago in $3. Already there $1 stroke me as genuinely gifted student with great potential as a research scientist. A year later I have been given a position at Ben-Gurion University where Helena is conducting her PhD research on desert dust storms with relation to human health. Helena has just the right combination of assertiveness and respect to make her a joy to work with. She leads her projects from the beginning while also being the data collected and analyzer. I would rank her in the top 2% of PhD students that I have met in the past five years in respect of her writing ability and research skills. In addition, among the group of outstanding undergraduate research students at the Aeolian Simulation Laboratory under the supervision of Dr Itzhak Katra, Helena ranks as the top overall. She is well-organized, quick to grasp new concepts, and always knows the objectives of a project.  During her studies, she analyzed the data set and had to learn to use the Geographic Information Systems (GIS) and she did it without a problem at all.

#+END_VERSE
