 #+TITLE:P031.MAIAC.France

* 0.Code details 
  :PROPERTIES:
  :ID:       23371787-acbe-41fa-8bab-5a2e91c1e61e
  :END:
** Matlab run (AOD and NDVI)
*** dependencies  
**** matlab helpers
$Note$ following matlab functions should be in your matlab script dir
file:/home/zeltak/org/files/Uni/Projects/code/C00Matlab

 jl2normaldate.m
 julian2date.m

**** create a lat and long file hdf files
for NDVI we need to use a tool called `eos2dump` we need to extract lat and long from 
₆In example₆ 

#+BEGIN_SRC sh
./eos2dump -c -2 MYD13A3.A2002182.h17v03.005.2007192192722.hdf  > h17v03.lon             
#+END_SRC

the AOD maiac file come with their own lat/long hdf files so it is unneeded 
*** AOD code
the code is devided into two main files:

*.run- the file you run which calls the function
*.read-the function itselfs with most of the code
The files for France are
file:/home/zeltak/org/files/Uni/Projects/code/P031.MAIAC.France/F_MCRun_france.m
file:/home/zeltak/org/files/Uni/Projects/code/P031.MAIAC.France/F_MCfunc_france.m

The code itself is commented so more datailed explenations on ecah step can be viwed in the code

the code outputs csv files located here:

file:/media/NAS/Uni/Data/MV3/Out/

*** NDVI code
the code is run from 1 file:

file:/home/zeltak/org/files/Uni/Projects/code/P031.MAIAC.France/MCRun_franceNDVI_pertile.m

The code itself is commented so more datailed explenations on ecah step can be viwed in the code

the code outputs csv files located here:

file:/media/NAS/Uni/Data/Europe/france/ndvi_france/out/

** R scripts
*** cs000 PBL extract
PBL was obtained through kees.
we used the following code to reshape the weird PBL format dbfs (from the shape files)
file:/media/NAS/Uni/org/files/Uni/Projects/code/P031.MAIAC.France/CS000_import_RAW_PBL_France.R

this takes care of the weird date as a column etc and creates a normal csv file per dbf file here:

file:/media/NAS/Uni/Data/Europe/france/pbl/final_csv/
*** CS001_spatial_temporal_DB.R
this scripts creates final files for pbl,ndvi, Land use, PM25/10 and met data.
the script explains the steps

file:/media/NAS/Uni/org/files/Uni/Projects/code/P031.MAIAC.France/CS001_spatial_temporal_DB.R

*** CS02_import_AOD.r

this script

file:/home/zeltak/org/files/Uni/Projects/code/P031.MAIAC.France/CS02_import_AOD.r

will load the matlab output for AOD ,clean the data , run EDA etc and output full and yearly RDS files outputed here:

file:/media/NAS/Uni/Projects/P031_MAIAC_France/2.work/WORKDIR/AOD.AQ.2003.rds

*** 004-clean station data and join to AOD
 
file:/media/NAS/Uni/org/files/Uni/Projects/code/P046.Israel_MAIAC/p004_stn_clean.r

We use this script to import all avilable israeli station data (PM,Met,co-pollutants etc)
we clean, run EDA import LU and join to AOD
this results in 2 all years files outputed for PM25 and PM10:
mod1.pm10all.RDS
mod1.pm25all.RDS

and per year files as well

*** 005 run mod1

file:/media/NAS/Uni/org/files/Uni/Projects/code/P046.Israel_MAIAC/p005_mod1.r

* 1.Data info
** general
France Satellite Models
Updated 6/5/2013

France_satellitemodel.mxd


Projection:
We are using the ETRS89_LAEA_Europe projection (also referred to as EPSG:3035).  This is the same projection used by the European Environment Agency for Corine Land Cover 2006 data.

Identifying satellite points in France:
\\DROBO\Shared_Data\France_LST\Stage 1\unclipped.sas7bdat includes latitudes and longitudes of satellite data.  N = 1,643,277

This file was exported to csv, then imported into a personal geodatabase and added as XY data to an ArcGIS 10.1 Map Document.  Latitudes and longitudes were assumed to be WGS 1984 datum.  (Note only 4 decimal places of latitudes and longitudes were available).  This XY data layer was exported as a file geodatabase feature class in the ETRS80_LAEA_Europe projection.

For boundaries of France ArcGIS 10 Data and Maps/Europe/background/admin.sdc/admin was used.  French administrative boundaries were exported into the ETRS80_LAEA_Europe projection.

Using this projection, points in unclipped.sas7bdat inFrance were set to 1 if they intersected the French administrative boundaries.  Gridid was set to ObjectId.  Feature class saved as france_satellite.gdb\ france_1st_st1_unclippedfc.  inFrance = 1 saved as france_1st_st1fc N = 626439

The results were exported as a csv file and imported into SAS as unclipped_infrance.sas7bdat.  

Elevation
\\DROBO\Shared_Data\France_LST\LU\GIS\elev\elevASC contains the raster file MNT250_L93_FRANCE.ASC
Cell size 250 m

Note MNT = Modele Numerique de Terrain  = Digital Elevation Model
Projection assumed to be same as data downloaded from http://professionnels.ign.fr/donnees-gratuites-re:

RGF93_Lambert_93
Authority: Custom

Projection: Lambert_Conformal_Conic
False_Easting: 700000.0
False_Northing: 6600000.0
Central_Meridian: 3.0
Standard_Parallel_1: 44.0
Standard_Parallel_2: 49.0
Latitude_Of_Origin: 46.5
Linear Unit: Meter (1.0)

Geographic Coordinate System: GCS_RGF_1993
Angular Unit: Degree (0.0174532925199433)
Prime Meridian: Greenwich (0.0)
Datum: D_RGF_1993
  Spheroid: GRS_1980
    Semimajor Axis: 6378137.0
    Semiminor Axis: 6356752.314140356
    Inverse Flattening: 298.257222101

Raster exported into file geodatabase in ETRS89 projection

Extract values to points without interpolation used 

Elevation = -9999 set to Null

Statistics
Count:	625749
Minimum:	0
Maximum:	4036
Mean:	340.373682
Standard Deviation:	421.700971
Nulls:	690

Population
[2000 population data is available, but I used 2006 instead
C:\gisdata\Europe\popu01clcv5.tif
2000 population density
Individuals per square kilometer
100 m resolution

Permalink to this version
F6907877-C585-45DE-B93F-E7FC0975DE2A 

http://link.springer.com/article/10.1007%2Fs11111-010-0108-y]

For Italy we have 2006 population
European Commission (Eurostat, Joint Research Centre and DG Regional Policy - REGIO-GIS).
GEOSTAT 1 km2 population grid

Selected from GEOSTAT_grid_EU_POP_2006_1kfgdb/gid_etrs89_laea_1k_ref_geostat_2006pntsfc points that intersect France and saved to France\GEOSTAT_grid_EU_POP_2006_1k_france.gdb
** GIS
*** projected data used
RGF93 / Lambert-93 
E:2154
*** port database
http://msi.nga.mil/NGAPortal/MSI.portal?_nfpb=true&_pageLabel=msi_portal_page_62&pubCode=0015
*** airport database
http://ourairports.com/data/
** Air tempreature data
Temperature and wind speed data came from measurements operated by Météo-France. I think Annick Auffray from Météo-France should be a co-author. Note that we need them to approve the paper before submission (it was explicitly written in our contract).
** pbl 
Planetary boundary layer data came from CNRS, Robert Vautard. If needed, he will add something in the paper about the model from which these data come from (50km resolution).
** land use 
I’ve got population density, hydrology, and traffic data from the IGN (Institut national de l'information géographique et forestière (IGN)) website but I will need to check how we should acknowledge them.




