* PAD
**** idea
By reading this paper it came back to my mind that there is another orphan cardiovascular disease in air pollution research: peripheral artery disease. This is usually due to atherosclerosis and narrowing of the arteries in the limbs and an lead to severe outcomes such as amputation.
It makes sense to be affected by air pollution, but last time I checked no one had published anything on this. With a large database and geospatial resolution, PAD would be an obvious one to look at.
**** data from antonella
when there is no 2, it means that they are created form first diagnosis, when there is the 2 it means that are created based on 1 and up to 5 secondary diagnosis
so the ones with the 2 should have higher numbers of hospitalizations    
**** Info
Peripheral artery disease (also called peripheral arterial disease) is a common circulatory problem in which narrowed arteries reduce blood flow to your limbs.
When you develop peripheral artery disease (PAD), your extremities — usually your legs — don't receive enough blood flow to keep up with demand. This causes symptoms, most notably leg pain when walking (intermittent claudication).
Peripheral artery disease is also likely to be a sign of a more widespread accumulation of fatty deposits in your arteries (atherosclerosis). This condition may be reducing blood flow to your heart and brain, as well as your legs.
Often, you can successfully treat peripheral artery disease by quitting tobacco, exercising and eating a healthy diet.
